"""Real Mongo/MCP/Java write boundaries; no model or persistent-kernel calls."""

from __future__ import annotations

import asyncio
import json
import sys
import threading
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import httpx
import pytest
import uvicorn
from fastapi import FastAPI
from pymongo import MongoClient

from agent.approval.middleware import HttpMCPWriteChannel
from agent.approval.models import ApprovalError, PendingStatus
from agent.approval.service import ApprovalService
from agent.approval.store import MongoPendingActionStore
from agent.persistence.indexes import ensure_application_indexes
from agent.planning.erp import read_erp_problem
from agent.planning.models import Demand, Plan, PlanLine
from agent.planning.orders import PlanningOrders
from agent.planning.revisions import revise_problem
from api_view.internal.approval import build_internal_router
from mcp_server.grants import verify_grant

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from fixtures import erp_service, loader, mcp_service, mongo_service  # noqa: E402

pytestmark = pytest.mark.integration
SECRET = "t39-test-grant-secret"
INTERNAL = "t39-test-internal-service-token"
OWNER = "demo-a"


@pytest.fixture(scope="module")
def db():
    settings = mongo_service.unique_settings("t39-" + uuid.uuid4().hex[:8])
    mongo_service.require_reachable(settings)
    with MongoClient(settings.mongo_uri, tz_aware=True, serverSelectionTimeoutMS=5000) as client:
        database = client[settings.database]
        ensure_application_indexes(database)
        try:
            yield database
        finally:
            mongo_service.drop_test_database(settings)


@pytest.fixture(scope="module")
def stack(db, tmp_path_factory):
    run_dir = tmp_path_factory.mktemp("t39-services")
    orders = PlanningOrders(db, grant_secret=SECRET)
    app = FastAPI()
    app.include_router(build_internal_router(service=orders.approvals, service_token=INTERNAL))
    port = mcp_service.free_port()
    server = uvicorn.Server(uvicorn.Config(app, host="127.0.0.1", port=port, log_level="warning"))
    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()
    try:
        deadline = time.monotonic() + 10
        while not server.started and thread.is_alive() and time.monotonic() < deadline:
            time.sleep(0.05)
        assert server.started, "real approval verification HTTP service failed to start"
        with erp_service.running_erp(run_dir / "erp", seed_path=loader.SEED_PATH) as erp:
            with mcp_service.running_gateway(
                run_dir / "mcp", erp_base_url=erp.base_url, erp_token=erp.token,
                grant_secret=SECRET, extra_env={
                    "MCP_APPROVAL_VERIFY_URL": f"http://127.0.0.1:{port}/internal/approvals/verify",
                    "INTERNAL_SERVICE_TOKEN": INTERNAL,
                },
            ) as gateway:
                yield erp, gateway, f"http://127.0.0.1:{port}/internal/approvals/verify"
    finally:
        server.should_exit = True
        thread.join(timeout=10)
        assert not thread.is_alive(), "test verification server did not stop"


@pytest.fixture
def scenario(db, stack):
    erp, gateway, _ = stack
    thread = "t39-" + uuid.uuid4().hex
    public = json.loads((loader.SEED_PATH.parent / "planning/goal-v1.json").read_text())
    demands = tuple(Demand.model_validate(d) for d in public["demands"])
    with erp.client() as client:
        problem = read_erp_problem(client, goal_id=thread, budget="2500.00", demands=demands)
    # Submitted candidate, deliberately not generated by a production planner/oracle.
    plan = Plan(goal_id=thread, revision=1, lines=(
        PlanLine(offer_id="S001:P001", quantity=42),
        PlanLine(offer_id="S001:P003", quantity=15),
        PlanLine(offer_id="S002:P004", quantity=23),
    ))
    orders = PlanningOrders(db, grant_secret=SECRET)
    orders.create(OWNER, thread, problem)
    return orders, thread, problem, plan, erp, HttpMCPWriteChannel(gateway.mcp_url)


def approve(orders, thread, action):
    return orders.approvals.approve(owner_user_id=OWNER, thread_id=thread,
                                   interrupt_id=action.interrupt_id, request_id=uuid.uuid4().hex)


def actual_orders(erp):
    with erp.client() as client:
        response = client.get("/api/erp/v1/orders", params={"page": 1, "page_size": 100})
        response.raise_for_status()
        return response.json()["data"]


def execute(orders, thread, action, channel):
    return asyncio.run(orders.execute(OWNER, thread, action.interrupt_id, channel=channel))


def test_two_orders_are_reviewed_individually_and_written_exactly_once(scenario):
    orders, thread, _, plan, erp, channel = scenario
    before = actual_orders(erp)["total"]
    actions = orders.prepare(OWNER, thread, plan)
    assert len(actions) == 2
    assert actual_orders(erp)["total"] == before
    results = []
    for i, action in enumerate(actions):
        approve(orders, thread, action)
        result = execute(orders, thread, action, channel)
        assert result["ok"], result
        assert actual_orders(erp)["total"] == before + i + 1
        assert execute(orders, thread, action, channel) == result
        results.append(result)
    written = {r["data"]["order_id"] for r in results}
    rows = [r for r in actual_orders(erp)["items"] if r["order_id"] in written]
    assert len(rows) == 2
    for action in actions:
        row = next(r for r in rows if r["supplier_id"] == action.payload["supplier_id"])
        assert row["note"] == action.payload["note"]
        assert sorted((r["part_id"], r["quantity"], r["unit_price"]) for r in row["lines"]) == sorted(
            (r["part_id"], r["quantity"], r["unit_price"]) for r in action.payload["lines"])
    assert actual_orders(erp)["total"] == before + 2
    assert len(orders.load(OWNER, thread, thread)["orders"]) == 2


def test_approving_first_does_not_approve_second(scenario):
    orders, thread, _, plan, erp, channel = scenario
    a, b = orders.prepare(OWNER, thread, plan)
    approve(orders, thread, a)
    before = actual_orders(erp)["total"]
    with pytest.raises(ApprovalError, match="individual"):
        execute(orders, thread, b, channel)
    assert actual_orders(erp)["total"] == before
    assert orders.approvals.store.find(OWNER, thread, b.interrupt_id).status == PendingStatus.PENDING


def test_rejected_order_never_writes(scenario):
    orders, thread, _, plan, erp, channel = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    orders.approvals.reject(owner_user_id=OWNER, thread_id=thread,
                            interrupt_id=a.interrupt_id, request_id="reject")
    before = actual_orders(erp)["total"]
    with pytest.raises(ApprovalError):
        execute(orders, thread, a, channel)
    assert actual_orders(erp)["total"] == before


@pytest.mark.parametrize("owner,other_thread", [("demo-b", False), (OWNER, True)])
def test_owner_and_thread_cannot_borrow_approval(scenario, owner, other_thread):
    orders, thread, _, plan, erp, channel = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    before = actual_orders(erp)["total"]
    with pytest.raises(ApprovalError):
        asyncio.run(orders.execute(owner, thread + "-other" if other_thread else thread,
                                    a.interrupt_id, channel=channel))
    assert actual_orders(erp)["total"] == before


def test_illegal_plan_creates_no_approvals(scenario):
    orders, thread, _, plan, _, _ = scenario
    bad = Plan(goal_id=thread, revision=1, lines=(PlanLine(offer_id="S001:P001", quantity=99),))
    with pytest.raises(ValueError, match="invalid plan"):
        orders.prepare(OWNER, thread, bad)
    assert orders.approvals.store.list_for_thread(OWNER, thread) == []
    assert orders.load(OWNER, thread, thread)["proposal"] is None


def test_revision_invalidates_approval_before_execution(scenario):
    orders, thread, problem, plan, erp, channel = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    orders.revise(OWNER, thread, revise_problem(problem, budget="2600.00").problem)
    before = actual_orders(erp)["total"]
    with pytest.raises(ApprovalError) as failure:
        execute(orders, thread, a, channel)
    assert failure.value.code == "STALE_PLAN"
    assert actual_orders(erp)["total"] == before


def test_same_revision_new_candidate_invalidates_old_approval(scenario):
    orders, thread, _, plan, _, channel = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    changed = Plan(goal_id=thread, revision=1, lines=plan.lines[:2])
    orders.prepare(OWNER, thread, changed)
    with pytest.raises(ApprovalError) as failure:
        execute(orders, thread, a, channel)
    assert failure.value.code == "STALE_PLAN"


def test_restart_reuses_recorded_actions_and_operation_ids(scenario, db):
    orders, thread, _, plan, _, _ = scenario
    first = orders.prepare(OWNER, thread, plan)
    restarted = PlanningOrders(db, grant_secret=SECRET)
    second = restarted.prepare(OWNER, thread, plan)
    assert [(a.interrupt_id, a.operation_id, a.payload_sha256) for a in first] == [
        (a.interrupt_id, a.operation_id, a.payload_sha256) for a in second]
    assert len(restarted.approvals.store.list_for_thread(OWNER, thread)) == 2


def test_execution_lease_blocks_revision_and_another_writer(scenario):
    orders, thread, problem, plan, _, channel = scenario
    a, b = orders.prepare(OWNER, thread, plan)
    approve(orders, thread, a)
    approve(orders, thread, b)

    async def observed(**kwargs):
        with pytest.raises(ApprovalError) as failure:
            orders.revise(OWNER, thread, revise_problem(problem, budget="2600.00").problem)
        assert failure.value.code == "REVISION_CONFLICT"
        with pytest.raises(ApprovalError) as failure:
            await orders.execute(OWNER, thread, b.interrupt_id, channel=channel)
        assert failure.value.code == "EXECUTION_BUSY"
        return await channel(**kwargs)

    assert execute(orders, thread, a, observed)["ok"]


def test_lost_response_keeps_lease_and_retry_uses_same_erp_operation(scenario, db):
    orders, thread, problem, plan, erp, channel = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    before = actual_orders(erp)["total"]

    async def response_lost(**kwargs):
        await channel(**kwargs)  # the real ERP has committed; client loses its response
        raise TimeoutError("injected loss after real write")

    with pytest.raises(TimeoutError):
        execute(orders, thread, a, response_lost)
    assert actual_orders(erp)["total"] == before + 1
    assert orders.load(OWNER, thread, thread)["execution"]["phase"] == "uncertain"
    with pytest.raises(ApprovalError):
        orders.revise(OWNER, thread, revise_problem(problem, budget="2600.00").problem)
    restarted = PlanningOrders(db, grant_secret=SECRET)
    result = execute(restarted, thread, a, channel)
    assert result["ok"]
    assert actual_orders(erp)["total"] == before + 1
    assert restarted.load(OWNER, thread, thread)["orders"][0]["operation_id"] == a.operation_id


def test_retryable_business_timeout_is_not_recorded_as_definite_failure(scenario):
    orders, thread, _, plan, _, _ = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)

    async def timeout(**kwargs):
        return {"ok": False, "error": {"code": "TIMEOUT", "retryable": True}}

    with pytest.raises(ApprovalError) as failure:
        execute(orders, thread, a, timeout)
    assert failure.value.code == "UNKNOWN_WRITE_RESULT"
    assert orders.load(OWNER, thread, thread)["execution"]["phase"] == "uncertain"
    assert orders.approvals.store.find(OWNER, thread, a.interrupt_id).status == PendingStatus.EXECUTING


def test_signed_old_grant_is_rejected_at_real_gateway_after_revision(scenario, stack):
    orders, thread, problem, plan, erp, channel = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    captured = {}

    async def capture(**kwargs):
        captured.update(kwargs)
        verified = orders.approvals.verify_internal(
            owner_user_id=OWNER, thread_id=thread, interrupt_id=a.interrupt_id,
            tool_name=a.tool_name, target=a.target, payload_sha256=a.payload_sha256,
            operation_id=a.operation_id,
        )
        assert verified.status == PendingStatus.EXECUTING
        # Definitive refusal lets the lease end, while the signed grant is retained.
        return {"ok": False, "error": {"code": "INVALID_ARGUMENT", "retryable": False}}

    execute(orders, thread, a, capture)
    orders.revise(OWNER, thread, revise_problem(problem, budget="2600.00").problem)
    with httpx.Client(trust_env=False, timeout=5) as client:
        check = client.post(stack[2], headers={"x-internal-service-token": INTERNAL}, json={
            "owner_user_id": OWNER, "thread_id": thread, "interrupt_id": a.interrupt_id,
            "tool_name": a.tool_name, "target": a.target, "payload_sha256": a.payload_sha256,
            "operation_id": a.operation_id,
        })
    assert check.status_code == 409
    assert check.json()["error"]["code"] == "STALE_PLAN"
    before = actual_orders(erp)["total"]
    result = asyncio.run(channel(**captured))
    if isinstance(result, list):
        result = json.loads(next(b["text"] for b in result if "text" in b))
    elif isinstance(result, str):
        result = json.loads(result)
    assert result["ok"] is False, result
    assert result["error"]["code"] == "APPROVAL_REQUIRED"
    assert actual_orders(erp)["total"] == before


def test_signed_planning_grant_cannot_write_without_verification_configuration(scenario, tmp_path):
    orders, thread, _, plan, erp, _ = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    before = actual_orders(erp)["total"]
    with mcp_service.running_gateway(
        tmp_path / "unconfigured-mcp", erp_base_url=erp.base_url, erp_token=erp.token,
        grant_secret=SECRET, extra_env={"MCP_APPROVAL_VERIFY_URL": ""},
    ) as gateway:
        result = execute(orders, thread, a, HttpMCPWriteChannel(gateway.mcp_url))
    assert result["ok"] is False
    assert result["error"]["code"] == "APPROVAL_VERIFICATION_UNAVAILABLE"
    assert actual_orders(erp)["total"] == before


def test_planning_grant_reference_is_signed_and_contains_no_model_owned_scope(scenario):
    orders, thread, _, plan, _, _ = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)

    async def inspect(**kwargs):
        grant = verify_grant(kwargs["grant"], secret=SECRET, expect_owner=OWNER,
                             expect_tool=a.tool_name, expect_target=a.target,
                             expect_payload_sha256=a.payload_sha256)
        assert grant.approval_ref == {"thread_id": thread, "interrupt_id": a.interrupt_id}
        return {"ok": False, "error": {"code": "TEST_REFUSAL", "retryable": False}}

    execute(orders, thread, a, inspect)


def test_partial_execution_prevents_new_full_purchase(scenario):
    orders, thread, problem, plan, _, channel = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    assert execute(orders, thread, a, channel)["ok"]
    changed = revise_problem(problem, budget="2600.00").problem
    orders.revise(OWNER, thread, changed)
    with pytest.raises(ApprovalError) as failure:
        orders.prepare(OWNER, thread, Plan(goal_id=thread, revision=2, lines=plan.lines))
    assert failure.value.code == "RECONCILIATION_REQUIRED"


def test_two_concurrent_approvals_have_one_winner(scenario):
    orders, thread, _, plan, _, _ = scenario
    a = orders.prepare(OWNER, thread, plan)[0]

    def decide(_):
        try:
            return approve(orders, thread, a).status
        except ApprovalError as failure:
            return failure.code

    with ThreadPoolExecutor(max_workers=2) as pool:
        results = list(pool.map(decide, range(2)))
    assert results.count(PendingStatus.APPROVED) == 1
    assert results.count("ALREADY_DECIDED") == 1


def test_missing_revision_guard_cannot_authorize_planning_action(scenario, db):
    orders, thread, _, plan, _, _ = scenario
    a = orders.prepare(OWNER, thread, plan)[0]
    approve(orders, thread, a)
    unguarded = ApprovalService(store=MongoPendingActionStore(db), grant_secret=SECRET)
    with pytest.raises(ApprovalError) as failure:
        unguarded.authorize(owner_user_id=OWNER, thread_id=thread,
                            interrupt_id=a.interrupt_id, tool_name="order_create", arguments=a.payload)
    assert failure.value.code == "PLANNING_UNAVAILABLE"
