/**
 * The backend as the UI sees it.
 *
 * Every call goes through `request`, so error handling and the ownership rule (the session
 * cookie, never a body field) live in one place. The streaming call is the exception: it
 * cannot use `request` because it must return frames as they arrive rather than a parsed
 * body.
 */

import { streamSse, type SseFrame } from './sse'

export const API_BASE = '/api'

export interface ApiError extends Error {
  status?: number
  code?: string
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${API_BASE}${path}`, {
    credentials: 'same-origin',
    headers: { 'Content-Type': 'application/json' },
    ...init,
  })
  if (!response.ok) {
    const error = await toError(response)
    throw error
  }
  const payload = (await response.json()) as { data: T }
  return payload.data
}

async function toError(response: Response): Promise<ApiError> {
  let detail = ''
  let code = ''
  try {
    const body = await response.json()
    detail = body?.detail ?? ''
    code = body?.error?.code ?? ''
  } catch {
    detail = ''
  }
  const error = new Error(detail || `请求失败（HTTP ${response.status}）`) as ApiError
  error.status = response.status
  error.code = code || statusCode(response.status)
  return error
}

/** Turn a status into the code the UI branches on, so callers do not string-match prose. */
function statusCode(status: number): string {
  if (status === 401) return 'UNAUTHENTICATED'
  if (status === 404) return 'NOT_FOUND'
  if (status === 409) return 'CONFLICT'
  if (status === 400) return 'INVALID_ARGUMENT'
  return 'HTTP_ERROR'
}

export interface ThreadSummary {
  thread_id: string
  title: string
  created_at: string
  updated_at: string
  message_count: number
  status: string
}

export interface ThreadDetail {
  thread_id: string
  title: string
  messages: Array<{ message_id: string; seq: number; role: string; content: string }>
  runs: Array<{ run_id: string; status: string; request_id: string; created_at: string }>
  todos: Array<{ content: string; status: string }>
  pending_interrupts: Array<{
    interrupt_id: string
    interrupt_type: string
    prompt: string
    candidates: Array<Record<string, unknown>>
  }>
  status: string
}

export interface ThreadState {
  thread_id: string
  run_id: string | null
  status: string
  todos: Array<{ content: string; status: string }>
  pending_interrupts: ThreadDetail['pending_interrupts']
  last_event_id: string | null
  cancel_requested: boolean
}

export const api = {
  session(userId: string) {
    return request<{ user_id: string; note: string }>('/demo/session', {
      method: 'POST',
      body: JSON.stringify({ user_id: userId }),
    })
  },

  listThreads(page = 1, pageSize = 20) {
    return request<{
      items: ThreadSummary[]
      total: number
      page: number
      page_size: number
    }>(`/history?page=${page}&page_size=${pageSize}`)
  },

  threadDetail(threadId: string) {
    return request<ThreadDetail>(`/history/${threadId}`)
  },

  deleteThread(threadId: string) {
    return request<{ thread_id: string; deleted: Record<string, number>; kept: string[] }>(
      `/history/${threadId}`,
      { method: 'DELETE' },
    )
  },

  threadState(threadId: string) {
    return request<ThreadState>(`/chat/${threadId}/state`)
  },

  cancel(threadId: string) {
    return request<{ thread_id: string; cancel_requested: boolean; note: string }>(
      `/chat/${threadId}/cancel`,
      { method: 'POST' },
    )
  },

  artifact(artifactId: string) {
    return request<{
      artifact_id: string
      name: string
      mime: string
      size: number
      download_ready: boolean
    }>(`/artifacts/${artifactId}`)
  },

  /** Start a turn. Yields frames; the caller drives the state machine. */
  stream(
    body: { request_id: string; message: string; thread_id?: string },
    options: { signal?: AbortSignal; fetchImpl?: typeof fetch } = {},
  ): AsyncGenerator<SseFrame> {
    return streamSse(`${API_BASE}/chat/stream`, body, options)
  },

  /** Answer an interrupt. Exactly one of `supplement` or `decisions` may be present. */
  resume(
    threadId: string,
    body: {
      request_id: string
      interrupt_id: string
      resume: { supplement?: string; decisions?: Array<{ type: string; message?: string }> }
    },
    options: { signal?: AbortSignal; fetchImpl?: typeof fetch } = {},
  ): AsyncGenerator<SseFrame> {
    return streamSse(`${API_BASE}/chat/${threadId}/resume`, body, options)
  },
}

/** A request id for one user action. Generated by the client, per the contract. */
export function newRequestId(): string {
  const cryptoObj = globalThis.crypto
  if (cryptoObj && 'randomUUID' in cryptoObj) return cryptoObj.randomUUID()
  return `req-${Date.now()}-${Math.floor(Math.random() * 1e9).toString(16)}`
}

/** Events whose `data` is a run status rather than something to display. */
export const TERMINAL_STATUSES = ['completed', 'interrupted', 'failed', 'cancelled'] as const

export type { SseFrame }
